name: Update Activity

on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Run script
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        pip install requests
        python scripts/update_readme.py

    - name: Commit changes
      run: |
        git config --global user.name "Guannan"
        git config --global user.email "happyguannan@gmail.com"
        git add README.md
        git commit -m "Update dynamic content"
        git push
